import 'main.dart';

final List<Book> allBooks = [
  Book(
    id: '10001',
    title: 'Modern C++ Tutorials',
    author: 'Ou Changkun',
    category: 'Beginner',
    imagePath: 'assets/cover/ModernC++Tutorials.jpg',
    description: 'This book assumes that readers are already familiar with traditional C++ (i.e. C++98 or earlier), at least they do not have any difficulty in reading traditional C++ code. In other words, those who have long experience in traditional C++ and people who desire to quickly understand the features of modern C++ in a short period are well suited to read the book.',
    pageCount: 92,
    pdfAssetPath: 'assets/pdfs/10001.pdf',
  ),
  Book(
    id: '10002',
    title: 'Introduction to Machine Learning with Python',
    author: 'Andreas C. Müller, Sarah Guido',
    category: 'Intermediate',
    imagePath: 'assets/cover/Introduction to ML with Python.png',
    description: 'This book is for current and aspiring machine learning practitioners looking to implement solutions to real-world machine learning problems. This is an introductory book requiring no previous knowledge of machine learning or artificial intelligence (AI)..',
    pageCount: 392,
    pdfAssetPath: 'assets/pdfs/10002.pdf',
  ),
  Book(
    id: '10003',
    title: 'Effective Modern C++',
    author: 'Scott Meyers',
    category: 'Intermediate',
    imagePath: 'assets/cover/EffectiveModernC++.jpg',
    description: 'For intermediate C++ programmers, this book focuses on effectively applying modern C++11 and C++14 features—like auto and lambdas—to write correct, efficient, and portable code, emphasizing the rationale behind best practices rather than just describing features.',
    pageCount: 451,
    pdfAssetPath: 'assets/pdfs/10003.pdf',
  ),
  Book(
    id: '10004',
    title: 'Open Data Structures',
    author: 'Pat Morin',
    category: 'Intermediate',
    imagePath: 'assets/cover/OpenDataStructure.jpg',
    description: 'This book offers a free and up-to-date alternative for introductory data structures courses, structured as an open-source project with downloadable source code and a Creative Commons Attribution license that permits free sharing and adaptation with simple attribution.',
    pageCount: 326,
    pdfAssetPath: 'assets/pdfs/10004.pdf',
  ),
  Book(
    id: '10005',
    title: 'The Complete Reference:SQL',
    author: 'James R.Groff, Paul N. Weinberg, Andrew J.Oppel',
    category: 'Expert',
    imagePath: 'assets/cover/SQLTheComplete.jpg',
    description: 'This third edition provides a comprehensive and in-depth understanding of the SQL language for technical and non-technical users, covering its history, standards, industry impact, and integration with object-based technologies, all supported by practical examples and a downloadable sample database..',
    pageCount: 986,
    pdfAssetPath: 'assets/pdfs/10005.pdf',
  ),
  Book(
    id: '10006',
    title: 'Modern C',
    author: 'Jens Gustedt',
    category: 'Beginner',
    imagePath: 'assets/cover/ModernC.jpg',
    description: 'This book is intended to change that general attitude, so it is organized in levels that reflect familiarity with the C language and programming in general. This structure may go against some habits of the book’s readers; in particular, it splits some difficult subjects (such as pointers) across levels in order to not swamp readers too early with the wrong information. We’ll explain the book’s organization in more detail shortly.',
    pageCount: 324,
    pdfAssetPath: 'assets/pdfs/10006.pdf',
  ),
  Book(
    id: '10007',
    title: 'Data Structures and Algorithms in C++',
    author: 'MICHAEL T. GOODRICH, ROBERTO TAMASSIA, DAVID MOUNT',
    category: 'C++', // Corrected category based on title
    imagePath: 'assets/cover/DataStructures&AlgorithmainC++.jpeg',
    description: 'This second edition of Data Structures and Algorithms in C++ is designed to provide an introduction to data structures and algorithms, including their design, analysis, and implementation. In terms of curricula based on the IEEE/ACM 2001 Computing Curriculum, this book is appropriate for use in the courses CS102 (I/O/B versions), CS103 (I/O/B versions), CS111 (A version), and CS112 (A/I/O/F/H versions). We discuss its use for such courses in more detail later in this preface.',
    pageCount: 738,
    pdfAssetPath: 'assets/pdfs/10007.pdf',
  ),
  Book(
    id: '10008',
    title: 'Beej\'s Guide to C Programming',
    author: 'Beej Jorgensen',
    category: 'C', // Corrected category based on title
    imagePath: 'assets/cover/BeejGuidetoProgramming.jpg',
    description: 'In the old days, C was a simpler language. A good number of the features contained in this book and a lot of the features in the Library Reference volume didn’t exist when K&R wrote the famous second edition of their book in 1988. Nevertheless, the language remains small at its core, and I hope I’ve presented it here in a way that starts with that simple core and builds outward.',
    pageCount: 325,
    pdfAssetPath: 'assets/pdfs/10008.pdf',
  ),
  Book(
    id: '10009',
    title: 'Algorithms in C',
    author: 'Robert Sedgewick',
    category: 'C', // Corrected category based on title
    imagePath: 'assets/cover/AlgorithmsinC.jpeg',
    description: 'This book is intended to survey the most important computer algorithms in use today and to teach fundamental techniques to the growing number of people in need of knowing them. It can be used as a textbook for a second, third, or fourth course in computer science, after students have acquired some programming skills and familiarity with computer systems, but before they have taken specialized courses in advanced areas of computer science or computer applications.',
    pageCount: 672,
    pdfAssetPath: 'assets/pdfs/10009.pdf',
  ),
  Book(
    id: '10010',
    title: 'A book on C',
    author: 'AL KELLEY, IRA POHL',
    category: 'C',
    imagePath: 'assets/cover/ABooksOnC.jpeg',
    description: 'This book assumes a general-purpose knowledge of the C language. It is intended for use in either a first or second programming course. However, it can be readily used in conjunction with courses on topics such as comparative programming languages, computationallinguistics, data structures, database systems, fractal geometry, graphicS, numerical analysis, operating systems, programming methodology, and scientific applications.',
    pageCount: 376,
    pdfAssetPath: 'assets/pdfs/10010.pdf',
  ),
  Book(
    id: '10011',
    title: 'Compiler Design in C',
    author: 'Allen I. Holub',
    category: 'C',
    imagePath: 'assets/cover/CompilerDesigninC.jpeg',
    description: 'This book presents the subject of Compiler Design in a way thats understandable to a programmer, rather than a mathematician. My basic premise is that the best way to learn how to write a compiler is to look at one in depth; the best way to understand the theory is to build tools that use that theory for practical ends. So, this book is built around working code that provides immediate practical examples of how given theories are applied. ',
    pageCount: 986,
    pdfAssetPath: 'assets/pdfs/10011.pdf',
  ),
  Book(
    id: '10012',
    title: 'Think Python',
    author: 'Allen Downey',
    category: 'Beginner',
    imagePath: 'assets/cover/ThinkPython.jpg',
    description: 'The goal of this book is to teach you to think like a computer scientist. This way of thinking combines some of the best features of mathematics, engineering, and natural science. Like mathematicians, computer scientists use formal languages to denote ideas (specifically computations). Like engineers, they design things, assembling components into systems and evaluating tradeoffs among alternatives. Like scientists, they observe the behavior of complex systems, form hypotheses, and test predictions.',
    pageCount: 1,
    pdfAssetPath: 'assets/pdf/10012.pdf',
  ),
  Book(
    id: '10013',
    title: 'The C Programming Language',
    author: 'Autonomous', // Corrected author
    category: 'C',
    imagePath: 'assets/cover/CProgramming.png',
    description: 'This book is a comprehensive guide to C programming, designed to help readers understand the fundamentals of one of the most powerful and widely used programming languages. It covers essential topics such as data types, control structures, functions, pointers, arrays, and memory management, making it suitable for both beginners and those looking to strengthen their coding skills.',
    pageCount: 290,
    pdfAssetPath: 'assets/pdfs/10013.pdf',
  ),
  Book(
    id: '10014',
    title: 'Think Stats : Exploratory Data Analysis in Python',
    author: 'Allen B. Downey',
    category: 'PYTHON',
    imagePath: 'assets/cover/ThinkStats.jpg',
    description: 'This book is an introduction to the practical tools of exploratory data analysis.',
    pageCount: 264,
    pdfAssetPath: 'assets/pdfs/10014.pdf',
  ),
  Book(
    id: '10015',
    title: 'Exploring JavaScript',
    author: 'Dr. Axel Rauschmayer',
    category: 'JAVASCRIPT',
    imagePath: 'assets/cover/ExploringJavascript.jpg',
    description: 'This book makes JavaScript easier for beginners by focusing on modern features, offering test-driven exercises, covering essential features up to ES2022, and providing optional advanced sections for deeper learning, with no prior JavaScript knowledge required but assuming basic programming skills.',
    pageCount: 405,
   pdfAssetPath: 'assets/pdfs/10015.pdf',
  ),
  Book(
    id: '10016',
    title: 'Eloquent JavaScript',
    author: 'Marijn Haverbeke',
    category: 'JAVASCRIPT',
    imagePath: 'assets/cover/EloquentJavaScript.jpg',
    description: 'This is a book about instructing computers. Computers are about as common as screwdrivers today, but they are quite a bit more complex, and making them do what you want them to do isn’t always easy.',
    pageCount: 435,
    pdfAssetPath: 'assets/pdfs/10016.pdf',
  ),
  Book(
    id: '10017',
    title: 'Deep JavaScript',
    author: 'Dr. Axel Rauschmayer',
    category: 'JAVASCRIPT',
    imagePath: 'assets/cover/DeepJavaScript.jpg',
    description: 'This book provides an in-depth exploration of JavaScript, teaching practical techniques, explaining how the language works based on the ECMAScript specification, and focusing on key topics within the language while excluding platform-specific features like browser APIs.',
    pageCount: 101,
    pdfAssetPath:'assets/pdfs/10017.pdf',
  ),
  Book(
    id: '10018',
    title: 'Tackling TypeScript',
    author: 'Dr. Axel Rauschmayer',
    category: 'JAVASCRIPT',
    imagePath: 'assets/cover/Tackling TypeScript.jpg',
    description: 'This book is divided into two parts: Part 1 offers a quick start to TypeScript, covering the essentials, while Part 2 explores the language in greater detail, complementing the official TypeScript handbook rather than serving as a reference.',
    pageCount: 67,
    pdfAssetPath: 'assets/pdfs/10018.pdf',
  ),
  Book(
    id: '10019',
    title: 'Shell Scripting with Node.js',
    author: 'Dr. Axel Rauschmayer',
    category: 'NODEJS',
    imagePath: 'assets/cover/ShellScripting.jpg',
    description: 'This book teaches shell scripting with Node.js, covering its architecture, event loop, and API, how to use npm for package management, writing cross-platform package scripts for development tasks, and deploying cross-platform shell scripts.',
    pageCount: 187,
    pdfAssetPath: 'assets/pdfs/10019.pdf',
  ),
  Book(
    id: '10020',
    title: 'Linux Commands Handbook',
    author: 'FLAVIO COPES',
    category: 'LINUX',
    imagePath: 'assets/cover/TheLinux.jpg',
    description: 'The Linux Handbook follows the 80/20 rule to quickly teach you 80% of Linux, aiming to get you up to speed fast, and is written by Flavio, a programmer who shares tutorials on his blog and organizes an annual bootcamp.',
    pageCount: 112,
    pdfAssetPath:'assets/pdfs/10020.pdf',
  ),
  Book(
    id: '10021',
    title: 'Ten Steps to Linux Survival',
    author: 'James Lehmer',
    category: 'LINUX',
    imagePath: 'assets/cover/TenStepstoLinuxSurvival.jpg',
    description: 'This book is aimed at Windows administrators, network admins, and developers with no prior Linux knowledge, helping them quickly learn basic steps to troubleshoot and manage Linux systems in emergency situations, like when a website goes down and no Linux experts are available.',
    pageCount: 74,
    pdfAssetPath: 'assets/pdfs/10021.pdf',
  ),
  Book(
    id: '10022',
    title: 'Linux 101 Hacks',
    author: 'Ramesh Natarajan',
    category: 'LINUX',
    imagePath: 'assets/cover/Linux101Hacks.jpg',
    description: 'This book features 101 hacks spread across 12 chapters, covering essential Linux commands, OpenSSH tips, date manipulation, command prompt customization, sysadmin tasks, package installation, bash history, and LAMP stack installation, all explained with easy-to-follow examples.',
    pageCount: 271,
    pdfAssetPath: 'assets/pdfs/10022.pdf',
  ),
  Book(
    id: '10023',
    title: 'Think Data Structures',
    author: 'Allen B. Downey',
    category: 'JAVA',
    imagePath: 'assets/cover/ThinkDataStructures.jpg',
    description: 'This book covers three topics: data structures using the Java Collections Framework (JCF), analyzing algorithms for performance and memory usage, and applying these concepts to build a simple web search engine.',
    pageCount: 187,
    pdfAssetPath: 'assets/pdfs/10023.pdf',
  ),
  Book(
    id: '10024',
    title: 'Introduction to Python Programming',
    author: 'UDAYAN DAS, AUBREY LAWSON, CHRIS MAYFIELD, NARGES ...',
    category: 'PYTHON',
    imagePath: 'assets/cover/IntroductiontoPython.png',
    description: 'The book Introduction to Python Programming by OpenStax provides an interactive learning experience for beginners, covering Python basics to advanced topics like classes, inheritance, and data science, with exercises, code runners, and video animations to reinforce understanding..',
    pageCount: 415,
    pdfAssetPath: 'assets/pdfs/10024.pdf',
  ),
];